### ISSUE TITLE
doesn't compile with libwireshark-2.4.4

### ISSUE THREAD

**Issue by prasincs** [sunwxg/golibwireshark#2]
I tried to copy the approach from https://github.com/sunwxg/decode_by_libwireshark
to get the golibwireshark to compile with wireshark-2.4.4, but I'm stuck on this

```
# github.com/sunwxg/golibwireshark                                                                                                     │
In file included from /usr/include/wireshark/epan/epan_dissect.h:31:0,                                                                 │clean:
                 from ././wireshark-2.4.4/lib.h:10,                                                                                    │        @rm -rf myshark
                 from ./golibwireshark.go:16:                                                                                          │
/usr/include/wireshark/epan/proto.h:125:27: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'void'                      │vagrant@mist-ap-dev:~/go/src/github.com/sunwxg/decode_by_libwireshark$ logout
 WS_DLL_PUBLIC WS_NORETURN void proto_report_dissector_bug(const char *message);                                                       │Connection to 127.0.0.1 closed.
                           ^
```

the code is in my fork at https://github.com/prasincs/golibwireshark

**Comment by sunwxg** [comment]
Now the golibwireshark only support wireshark 1.12.8.
I will update it to support 2.4.4 soon.
